---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/health":
    get:
      summary: list healths
      responses:
        '200':
          description: successful
  "/api/v1/weather/historical":
    get:
      summary: list historicals
      responses:
        '200':
          description: successful
  "/api/v1/weather/historical/max":
    get:
      summary: max historical
      responses:
        '200':
          description: successful
  "/api/v1/weather/historical/min":
    get:
      summary: min historical
      responses:
        '200':
          description: successful
  "/api/v1/weather/historical/avg":
    get:
      summary: avg historical
      responses:
        '200':
          description: successful
  "/api/v1/weather/current":
    get:
      summary: current weather
      responses:
        '200':
          description: successful
  "/api/v1/weather/by_time":
    get:
      summary: by_time weather
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.example.com
